### ISSUE TITLE
IDE errors for v1.5.9

### ISSUE THREAD

**Issue by betaSavvy** [xdrop/night-owl-jetbrains#50]
## Expected Behaviour

- What is the behaviour you were _expecting_

No error.

## Current Behaviour

- What is the behaviour you are _currently experiencing_

Exception error when PHPStorm starts.

- What is the plugin _missing_ right now

None

- Stacktrace error message

```
Do not request resource from classloader using path with leading slash

com.intellij.diagnostic.PluginException: /themes/nightowl.xml [Plugin: me.xdrop.night-owl]
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:472)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:439)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at com.mallowigi.idea.MTBundledThemesManager.loadBundledTheme(MTBundledThemesManager.java:150)
	at com.mallowigi.idea.MTBundledThemesManager.installBundledTheme(MTBundledThemesManager.java:113)
	at com.mallowigi.idea.MTBundledThemesManager.loadBundledThemes(MTBundledThemesManager.java:108)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.java:115)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated(MTLafComponent.java:74)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:624)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy39.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt:98)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:77)
	at com.intellij.idea.ApplicationLoader$startApp$3.run(ApplicationLoader.kt:185)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
## System details

**Plugin Version:** 1.5.9

```
PhpStorm 2021.2.1
Build #PS-212.5080.71, built on August 26, 2021
Runtime version: 11.0.11+9-b1504.16 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
izhangzhihao.rainbow.brackets (6.21), com.chrisrm.idea.MaterialThemeUI (6.9.0), me.xdrop.night-owl (1.5.9), 
```

**Comment by andfinally** [comment]
Came here to report the same thing with PhpStorm 2021.2.2 amd theme 1.5.9. The theme still seems to function though. 

Thanks for your work on this, BTW, I love the Night Owl theme and use it always! ❤️
